import { Geist, Geist_Mono } from "next/font/google"; // Font
import "./globals.css"; //Css file for global styles
import Header from "./components/Header"; // Header component
import Footer from "./components/footer"; // Footer component
import "bootstrap/dist/css/bootstrap.min.css"; // Bootstrap CSS
import BootstrapProvider from "./BootstrapProvider"; // Import the component to use bootstrap

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// Landing page Layout. Every page of the website will have this structure
export default function RootLayout({ children }) {
    return (
        <BootstrapProvider>
            <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <Header />
                    {children}
                    <Footer />
                </body>
            </html>
        </BootstrapProvider>
    );
}
